language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

branches:
  only:
    - master
    - 1.0.0.rc1

addons:
  code_climate:
    repo_token: 88bff0ece428b1a8027cbf9b03512de380ed6850ca418c85006ac813b5260ddc

script: bundle exec rspec spec

notifications:
  recipients:
    - fernando@motonow.com.br
    - rafael@motonow.com.br
