language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

branches:
  only:
    - master
    - 1.0.0.rc1

script: bundle exec rspec spec

notifications:
  recipients:
    - fernando@motonow.com.br
    - rafael@motonow.com.br
